# Generated by Django 5.2.15 on 2026-06-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Document', 'Barangay Certificate'), ('Registration', 'Barangay Registration'), ('Permit', 'Permit')], max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('Indigency', 'Indigency'), ('Residency', 'Residency'), ('Clearance', 'Clearance')], max_length=20)),
                ('permit_type', models.CharField(blank=True, choices=[('Building', 'Building'), ('Business', 'Business')], max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Released', 'Released'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='residents.resident')),
            ],
            options={
                'ordering': ['-date_applied', '-updated_at'],
            },
        ),
    ]
